### ISSUE TITLE
"Create window failed" error message with large number of panes

### ISSUE THREAD

**Issue by bruno-** [ChrisJohnsen/tmux-MacOSX-pasteboard#30]
Hi,
first of all, thanks for making and maintaining this project.

I'm not sure the error I'm getting is related to this project, but maybe you'll be able to point me in the right direction?
Anyway here's the description and the details:
- in tmux, when I try to create a new window or a new pane I get this error:
  
  ```
  Create window failed: reattach-to-user-namespace -l /usr/local/bin/bash: Device not configured
  ```
- I'm on OS X 10.9.4, tmux `1.9a`
- I'm running 2 separate tmux servers. One with 69 panes, the other with 56, a total of 125 panes. I might be hitting some limit with this.
- I just noticed I can't even open regular (non tmux) `Terminal.app` windows. I'm getting this error in the terminal:
  
  ```
  [forkpty: Device not configured]
  [Could not create a new process and open a pseudo-tty.]
  ```

I'd appreciate any pointer on this and how to make things running - thanks!
Feel free to close the issue if it's not related to this project.

**Comment by adoyle-h** [comment]
Great answer! It's very useful. Thanks :+1:
