### ISSUE TITLE
I can't use pbcopy on tmux.

### ISSUE THREAD

**Issue by umiyosh** [ChrisJohnsen/tmux-MacOSX-pasteboard#32]
I had upgraded OSX from Mavericks to Yosemite and re-installed reattach-to-user-namespace.
Now , I can use pbcopy as CLI command, but I can't use pbcopy on tmux. my settings is like this.

``` conf
set-option -g default-command "reattach-to-user-namespace -l zsh"
bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"
bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
```

my tmux version is 1.9a and reattach-to-user-namespace version is 2.3.
I can't fix problem.
any idea?

**Comment by goofansu** [comment]
@ChrisJohnsen Hi, I have the same problem but something is different.

Tmux version: 1.9a
System: OS X 10.9.5

`echo foo | reattach-to-user-namespace pbcopy` is right. But when in copy-mode, it has no effect.

FYI,

``` bash
~ ❯❯❯ tmux showenv -g PATH
PATH=/usr/bin:/bin:/usr/sbin:/sbin
~ ❯❯❯ which reattach-to-user-namespace
/usr/local/bin/reattach-to-user-namespace
~ ❯❯❯ echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
```
