### ISSUE TITLE
Unable to run `display notification` through `osascript` in tmux

### ISSUE THREAD

**Issue by mmwtsn** [ChrisJohnsen/tmux-MacOSX-pasteboard#40]
Running the following fails when run under tmux (at least) on OS X 10.10:

```bash
osascript -e 'display notification "This is a test message." with title "Test"'
```
However, when run in a Bash shell without tmux it works fine. Any ideas?

This may very well be out of scope for this project but this was mentioned as a potential solution in [a StackOverflow question](http://apple.stackexchange.com/questions/174779/unable-to-run-display-notification-using-osascript-in-a-tmux-session).

**Comment by ChrisJohnsen** [comment]
The wrapper program does help this case for me (10.10.3). Of the following two commands (run inside a *tmux* session), only the second one actually produces a notification:

    osascript -e 'display notification "Test (from tmux)"'
    reattach-to-user-namespace osascript -e 'display notification "Test (from tmux, reattached)"'

However, I would not be surprised if this is similar to #37, where the wrapper stops helping if the *tmux* server outlives your GUI login.

If including the wrapper (like the second command above) does not help, you could try this command (from outside any existing *tmux* session: e.g. a plain *Terminal* or *iTerm* window):

    tmux -L fresh new "reattach-to-user-namespace osascript -e 'display notification \"Test (from fresh tmux, reattached)\"'"

(where no *tmux* server is currently running under the name `fresh`)

If that command works, then restarting your *tmux* server should help (at least until you logout of you GUI session again), but this means quitting any existing sessions, so you would have to recreate any long-running sessions that you want to have back.

Unfortunately, I do not know of a way to fix this “after GUI relogin” scenario. This stuff has always been almost completely undocumented. Apple fixed pasteboard access (without the wrapper, even after a GUI relogin) but there appear to be several other areas like this remain half broken (i.e. fixable with the wrapper program) before GUI logout and fully broken after GUI relogin).

**Comment by mmwtsn** [comment]
This is really helpful.

Including the wrapper did the trick.

These issues occasionally end up _being_ the documentation for certain corner cases. Thank you for the detailed answer. I'll head over and update the StackOverflow questions.
