### ISSUE TITLE
El Capitan Support

### ISSUE THREAD

**Issue by JoshTheGeek** [ChrisJohnsen/tmux-MacOSX-pasteboard#42]
Does this support El Capitan?

**Comment by ChrisJohnsen** [comment]
I have not tried OS X 10.11 El Capitan, but @lembacon provided pull request #39 along those lines (merged into [v2.4][2.4]).

[2.4]: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/tree/v2.4

Note, however, that you may not actually need the wrapper program under Yosemite *or* El Capitan; I stopped using it on Yosemite near the beginning of 2015. It is apparently still helpful in some situations, but it is no longer necessary for (my) primary use case: pasteboard access.

**Comment by JoshTheGeek** [comment]
Wow, I was completely unaware that pasteboard worked now. That's awesome! Thank you for the response.
