### ISSUE TITLE
Yosemite tmux oddities

### ISSUE THREAD

**Issue by keith** [ChrisJohnsen/tmux-MacOSX-pasteboard#43]
After seeing the note in the README about no longer needing reattach-to-user-namespace on Yosemite I removed it from my configuration. I just noticed that without it AddressBook access from the command line is broken.

I use mutt and a very simple [contacts script](https://github.com/keith/dotfiles/blob/c91eb69e2555f548b6d138955a3da9ae0d5f4dae/bin/contacts) to access the OS X contacts database to search for mail recipients, I was finally able to narrow this down to no longer using reattach-to-user-namespace since it works in both Terminal.app and iTerm without tmux, and doesn't work inside tmux unless I'm using reattach-to-user-namespace.

Nothing particularly actionable here, I haven't tried this on El Capitan yet, but I thought it was worth documenting this one case that might still be affected by this OS bug

**Comment by ChrisJohnsen** [comment]
Thanks for the feedback! I have added a new entry to the “Beyond Pasteboard Access” section of `Usage.md`.

**Comment by keith** [comment]
Thanks!

**Comment by keith** [comment]
Worth noting that without reattach-to-user-namespace this same issue appears on El Capitan :sob:

**Comment by keith** [comment]
Just a heads up that this is still a problem on Sierra

**Comment by keith** [comment]
It actually seems like even when building HEAD of this repo reminders and contact access is broken in tmux on Sierra 😭

**Comment by keith** [comment]
This is easy to reproduce with these steps:

1. Open a new Terminal.app window (without tmux)
1. Run `swift` enter (the first time you will be asked for permissions):

```
import AddressBook
ABAddressBook.shared()
```

Then launch tmux, and do the same. The first time you will see some output about that call creating an object successfully. The second you will see nil.

Successful example in terminal:

<img width="890" alt="screen shot 2016-09-20 at 20 19 47" src="https://cloud.githubusercontent.com/assets/283886/18693434/a58fe07c-7f6f-11e6-982c-c55a4850bf10.png">

Failed example in tmux:

<img width="890" alt="screen shot 2016-09-20 at 20 20 06" src="https://cloud.githubusercontent.com/assets/283886/18693446/b2bb3846-7f6f-11e6-8f9f-67c6b831ec8b.png">

**Comment by keith** [comment]
The second screenshot in that last example was actually still using reattach-to-user-namespace. Without using that at all you get a tiny bit more failure logging:

```

**Comment by keith** [comment]
Also possibly related: https://github.com/tmux/tmux/issues/543

**Comment by keith** [comment]
Here's the relevant syslog from the time that this fails as well:

```
default	20:40:46.484186 -0400	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	20:40:46.485169 -0400	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	20:40:46.485223 -0400	tccd	CSSM Exception: -2147411889 CSSMERR_CL_UNKNOWN_TAG
default	20:40:46.485271 -0400	tccd	MacOS error: -67050
error	20:40:46.485320 -0400	tccd	Refusing TCCAccessRequest for service kTCCServiceAddressBook from client com.apple.Terminal in background session
```

**Comment by florianbeer** [comment]
I am using `lbdb` for contacts lookup in mutt and have the same problem. Even with `reattach-to-user-namespace` I don't get access to AddressBook inside tmux. In a plain terminal everything works as it should.

Just commenting here so I get a notification, in case any of you finds a solution.

**Comment by keith** [comment]
@ChrisJohnsen can we reopen this one? If there's somewhere you think of that I can start trying to figure this out please let me know and I'll see what I can do!

**Comment by ChrisJohnsen** [comment]
Sure, it can be re-opend. Technically, this is a different problem from the initial report (then: not working unless reattached; now: not working even if reattached).

The syslog message makes me think that it might work if we could reattach to different session type. There were other session constants (`VPROCMGR_SESSION_…` in [vproc_priv.h][h]) in the last visible-source release, but that was back in 10.9, and some things definitely changed in the subsequent releases. The code path for non-`"Background"` in `_vprocmgr_move_subset_to_user` in [libvproc.c][c] was a bit different, so it may be difficult to re-create it.

[h]: http://opensource.apple.com/source/launchd/launchd-842.1.4/liblaunch/vproc_priv.h
[c]: http://opensource.apple.com/source/launchd/launchd-842.1.4/liblaunch/libvproc.c

I do not yet have Sierra installed, but those are my best guesses as to directions to investigate.

**Comment by keith** [comment]
Thanks, I'll look into those as soon as I can.

I can also open a new issue if you'd prefer.


--
Keith Smiley

**Comment by keith** [comment]
So it seems like as of 10.12.1 (16B2555) everything is working as expected again. Reminders access and contacts access seem to be back up and running. I guess we'll just have to chalk that one up to software ¯\\_(ツ)_/¯
