### ISSUE TITLE
Shows warning on El Capitan

### ISSUE THREAD

**Issue by hotpxl** [ChrisJohnsen/tmux-MacOSX-pasteboard#44]
On `reattach-to-user-namspace.c:120`, the comment says 10.11 should return 14.0.0 by `uname -r`, but it is in fact 15.0.0. That's the reason it triggers line 131 and outputs a warning.

Currently I haven't encountered any issue on El Capitan, so I guess it's OK to just suppress the warning?

**Comment by ChrisJohnsen** [comment]
I have not installed El Capitan, but on my 10.10.5 system, `uname -r` reports 14.5.0. If 10.11(.0) reports 15.0.0, then it does not look like it has diverged from the expected pattern (Darwin x.y.z runs Mac OS X 10.(x-4).y).

Check your `reattach-to-user-namespace -v`. The latest version is 2.4 (the primary change was to update the version check to not carp about running on 10.11).

**Comment by hotpxl** [comment]
Oh yeah. I downloaded it from Macports, but it's outdated. I guess I'll have to contact the maintainer about this. Thanks!

**Comment by hotpxl** [comment]
I tried using tmux under El Capitan, and pbpaste works fine with this. I guess we don't need to reattach anymore under El Capitan?

**Comment by hotpxl** [comment]
OK now i see `usage.md` and how everything works. thx

**Comment by ChrisJohnsen** [comment]
@hotpxl Sort of. As noted in 2c4d0aaf3d4af3b34f2890dd3613145e8808ba2a, starting in Yosemite the wrapper does not seem necessary for pasteboard access, but it is still [helpful in other contexts][other] (e.g. #43, even under [El Capitan][43-elcap]).

[other]: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/blob/master/Usage.md#beyond-pasteboard-access
[43-elcap]: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/43#issuecomment-138733609
