### ISSUE TITLE
Seems El Capitan (OS X 10.11) broke functionality

### ISSUE THREAD

**Issue by berinle** [ChrisJohnsen/tmux-MacOSX-pasteboard#45]
Hi,
I am running OS X El Capitan (10.11), and reattach-to-user-namespace isn't working.

I get this warning anytime I launch a new tmux window

    warning: reattach-to-user-namespace: unsupported new OS, trying as if it were 10.10

Can you please advise?

Thanks

**Comment by ChrisJohnsen** [comment]
It should still be working (as much as it ever does), but you can suppress that warning by upgrading to the latest version (2.4; check yours with `reattach-to-user-namespace -v`).

**Comment by berinle** [comment]
Hmmm, ok. Thanks for the prompt response. With regards to upgrading...


➜  ~  brew upgrade reattach-to-user-namespace
Error: reattach-to-user-namespace 2.4 already installed
➜  ~  reattach-to-user-namespace -v
reattach-to-user-namespace version 2.3
    Supported OSes: OS X 10.5-10.10
➜  ~
➜  ~  which reattach-to-user-namespace
/usr/local/bin/reattach-to-user-namespace

So, it says am I already on 2.4 but -v is printing 2.3.

**Comment by ChrisJohnsen** [comment]
I am not sure why your Homebrew thinks it has version 2.4, but that sure looks like an old binary. Here is what a current version should show:

    % ./reattach-to-user-namespace -v
    ./reattach-to-user-namespace version 2.4
        Supported OSes: OS X 10.5-10.11

It should say that it is version `2.4` and that is supports `10.5-10.11`.

I do not use Homebrew, so there may be some more convenient way to force a rebuild, but I would try uninstalling and reinstalling that package.

**Comment by berinle** [comment]
Uninstalled and reinstalled. Works fine now. Thanks!

**Comment by amirrajan** [comment]
Uninstall and reinstall worked or me too.
