### ISSUE TITLE
Using `exec reattach-to-username -l <your favorite shell>` on README

### ISSUE THREAD

**Issue by gregory-nisbet** [ChrisJohnsen/tmux-MacOSX-pasteboard#49]
I've been using `set-option -g default-command "reattach-to-user-namespace -l /bin/tcsh"` for a little while now and I've noticed that every shell I spawn requires two processes. (On a somewhat unrelated note, Is there a way to configure to tmux to either use `/bin/sh` for executing commands regardless of my login shell or to pass `-f` as an argument to prevent `tcsh` from reading my config file twice?)

    % pstree | grep -n 'tmux\|tcsh' 

```
70: | |   \-+= 00527 gregory.nisbet -tcsh
71: | |     \--= 12622 gregory.nisbet tmux
101: | |   \--= 00439 gregory.nisbet -tcsh
238: \-+= 12624 gregory.nisbet tmux
239:   |-+= 12625 gregory.nisbet -csh -c reattach-to-user-namespace -l /bin/tcsh
240:   | \-+= 12629 gregory.nisbet -tcsh
243:   |   \--- 12849 gregory.nisbet grep -n tmux\|tcsh
244:   |-+= 12830 gregory.nisbet -csh -c reattach-to-user-namespace -l /bin/tcsh
245:   | \--= 12834 gregory.nisbet -tcsh
246:   \-+= 12675 gregory.nisbet -csh -c reattach-to-user-namespace -l /bin/tcsh
247:     \--= 12679 gregory.nisbet -tcsh
```

The clipboard seems to still work as intended if I replace the command with

    set-option -g default-command "exec reattach-to-user-namespace -l /bin/tcsh"

As opposed to disabling it entirely which causes

    % echo hi there | pbcopy

to exit with a nonzero exit status.

**Comment by ChrisJohnsen** [comment]
`reattach-to-user-namespace` does not really control any of these effects.

*tmux* uses `default-shell` as the shell to launch `default-command` (i.e. the argv given to exec is effectively [`{{default-shell}}`, `-c`, `{{default-command}}`] ). You could set `default-shell` to `/bin/sh`, but *tmux* also sets SHELL to whatever is used in `default-shell`. This will not directly affect your `default-command` (unless it behaves differently for different values of SHELL), but it might affect other things (like shells started from inside other programs); maybe you could set it back to your preferred value via your shell’s configuration.

Starting `default-command` with `exec` is fine if your effective shell does not automatically exec when it is given a single command in its `-c` argument.

**Comment by gregory-nisbet** [comment]
@ChrisJohnsen 
Thanks for the explanation. I guess most sane shells will interpret the `-c` flag a little differently than tcsh does and there'd be no reason to include `exec` in the recommended configuration in the README since it likely doesn't affect bash, zsh, fish etc.
