### ISSUE TITLE
Sierra Warning Message

### ISSUE THREAD

**Issue by zacheryph** [ChrisJohnsen/tmux-MacOSX-pasteboard#52]
Get same message from #45 on macOS Sierra.

`warning: reattach-to-user-namespace: unsupported new OS, trying as if it were 10.10`

**Comment by ChrisJohnsen** [comment]
Updated code is available in the [`pu` branch][pu] (“proposed updates”).

See #50. I am waiting for the betas to mature (to make sure additional changes are not needed) before making a final release.

[pu]: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/tree/pu

**Comment by mvanbaak** [comment]
Can you please merge it to master so brew users can install it using `brew install --HEAD reattach-to-user-namespace`

Thank you!

**Comment by felippenardi** [comment]
@ChrisJohnsen Please merge it to master

**Comment by great2soul** [comment]
brew upgrade reattach-to-user-namespace
fix this issue

**Comment by felippenardi** [comment]
@great2soul I'm getting this error message:

```
$ brew upgrade reattach-to-user-namespace
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
Error: reattach-to-user-namespace 2.4 already installed
```

**Comment by barm4ley** [comment]
@felippenardi 
run `brew update`
but first make /usr/local writable
