### ISSUE TITLE
Required again on sierra

### ISSUE THREAD

**Issue by purge** [ChrisJohnsen/tmux-MacOSX-pasteboard#53]
Looks like macos sierra requires this hack again. If others can confirm this, I will provide a patch to the readme to explaining this.

**Comment by dalizard** [comment]
It seems to be broken (again) under macOS Sierra.

**Comment by maletor** [comment]
100% confirmed. 

😞

**Comment by rtfpessoa** [comment]
The current fix that worked was to use: `reattach-to-user-namespace pbcopy` always.
So it is probably reattaching every time, but works.

Do you have any better workarounds?

**Comment by maletor** [comment]
Nothing besides what's already mentioned in the README. I sent feedback to Apple about the regression, but I am pessimistic that will do anything.
