### ISSUE TITLE
This no longer works on macOS Sierra

### ISSUE THREAD

**Issue by jsatk** [ChrisJohnsen/tmux-MacOSX-pasteboard#56]
Unfortunately it appears this is broken on Sierra. I've tried everything I can think of and read through all issues on here, but still haven't found a solution. Anyone know of a solution or a timeline on a fix?

**Comment by supermarin** [comment]
are you sure it's Sierra and not tmux --HEAD that broke the whole visual mode?

**Comment by jsatk** [comment]
I just ran `brew uninstall tmux reattach-user-to-namespace && brew install tmux reattach-user-to-namespace` and it's still not working :(

**Comment by jsatk** [comment]
I have this in my `~/.tmux.conf`. And *this* is working. If I scroll up in tmux and highlight some text and then press `^b y` it copies it to my clipboard.
```tmux
# copy to Mac OSX pasteboard
if -b 'which -s reattach-to-user-namespace' 'bind y run "tmux save-buffer - | reattach-to-user-namespace pbcopy"'
```

However, before Sierra anytime I highlighted text in tmux it was automatically copied to my clipboard (like how native iTerm behaves).

I believe this line achieved that.

```tmux
# see https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
if 'which -s reattach-to-user-namespace' 'set -g default-command "reattach-to-user-namespace $SHELL -l"'
```

Forgive me if any of this is misinformed. I'm a recent tmux convert. Only got about 3 months of experience with it under my belt.

**Comment by supermarin** [comment]
Sorry what I've meant is - it might be a tmux issue and not reattach-to-user-namespace.
I can look on the Sierra computer tonight, as I'm still on El Capitan on the work laptop.

What happened in tmux/tmux is they're rewriting the visual mode API, so the old bindings won't work anymore. Try `brew uninstall --force tmux` and installing version 2.2

**Comment by jsatk** [comment]
Thanks so much for your help @supermarin! Will try that.

**Comment by MarceloCajueiro** [comment]
Any update @jsatk ?

I'm having the same issue here.

**Comment by jsatk** [comment]
@MarceloCajueiro unfortunately it did not work. Again, once I highlight i can run a tmux command to copy to clipboard, but it used to automagically copy on highlight, which I want back.

**Comment by chischaschos** [comment]
Look at https://github.com/tmux/tmux/issues/543. I followed the thread and solved the issue by basically adding these two settings:

```
set -g default-shell $SHELL
set -g default-command "reattach-to-user-namespace -l ${SHELL}"
```

And then restarting my tmux server:

```
 tmux kill-server
```

Hope this helps.

**Comment by jsatk** [comment]
@chischaschos Still doesn't work. Again, I can send text I've highlighted in tmux (which sends it to the save-buffer in tmux) to `pbcopy` with prefix + y. This is the line that does that.

`if -b 'which -s reattach-to-user-namespace' 'bind y run "tmux save-buffer - | reattach-to-user-namespace pbcopy"'`

Previously, however, it *automatically* sent any text I highlight with the mouse in tmux to the clipboard. Meaning, anything that went to the save buffer got sent to `pbcopy` automatically. 

That stopped working in Sierra, but my `tmux.conf` didn't change.

**Comment by ddickstein** [comment]
I'm running into the same problem on OS X 10.12., tmux 2.3, and reattach-to-user-namespace 2.5.

**Comment by mttrs** [comment]
In my case, it works when I install it with the option below.
```
# install with --with-wrap-pbcopy-and-pbpastebr option
% brew install reattach-to-user-namespace --with-wrap-pbcopy-and-pbpastebr

# See available options
% brew options reattach-to-user-namespace
--with-wrap-launchctl
	Include wrapper for launchctl with this fix
--with-wrap-pbcopy-and-pbpaste
	Include wrappers for pbcopy/pbpaste that shim in this fix
--HEAD
	Install HEAD version
```

**Comment by mgenov** [comment]
I'm encountered the same issue even when "Applications in terminal may access clipboard" is selected. 

Here is my environment:
```
iTerm 3.0.15
tmux 2.5
reattach-to-user-namespace version 2.6
OS Sierra: 10.12.5
```



This is added on top of my config file: 
```
set -g default-shell $SHELL
set-option -g default-command "reattach-to-user-namespace -l zsh"
bind-key -T copy-mode M-w send-keys -X copy-pipe 'reattach-to-user-namespace pbcopy'
bind-key -T copy-mode Enter send-keys -X copy-pipe 'reattach-to-user-namespace pbcopy'
```

And the clipboard is not working as expected. When I run: 
```
tmux showb
```
is showing my last selection

When doing:
```bash
tmux showb | pbcopy 
```

the content goes to the clipboard and I'm able to paste the content outside of the terminal and in the terminal.

**Comment by ghasshee** [comment]
I had the same issue


~~~
set-option -g default-shell "${SHELL}"
set-option -g default-command      "reattach-to-user-namespace -l ${SHELL}"

# Copy
bind-key >  save-buffer $HOME/.tmux-buffer \; \
            run 'pbcopy < $HOME/.tmux-buffer' \; \
            display-message "Copied to clipboard."
~~~


and fixed like this.

~~~
set-option -g default-shell "${SHELL}"
set-option -g default-command      "reattach-to-user-namespace -l ${SHELL}"

# Copy
bind-key >  save-buffer $HOME/.tmux-buffer \; \
            run 'reattach-to-user-namespace pbcopy < $HOME/.tmux-buffer' \; \
            display-message "Copied to clipboard."
~~~


oh, shit ! it worked !

**Comment by fmendez** [comment]
I had the same issue after upgrading to High Sierra. All I had to do was:

`brew upgrade reattach-to-user-namespace `

**Comment by jsatk** [comment]
This appears fixed now.
