### ISSUE TITLE
tmux ignoring .bash_profile configurations after installing

### ISSUE THREAD

**Issue by lawhorkl** [ChrisJohnsen/tmux-MacOSX-pasteboard#62]
Running: Mac OSX Sierra 10.12.3 MBP 2012, tmux 2.3, latest homebrow version of tmux osx pasteboard

I have several configs in .bash_profile used for various things like integrating SilverSearcher, git tab autocomplete, and customizing the bash prompt to include: user & hostname, current working directory, and git branch information (branch name, uncommitted changes, added changes, merge information, etc.)

When running tmux with this wrapper the git autocomplete and silver searcher works fine, however my changes to the bash prompt are replaced by this: `kyles-mbp-2%`. I'd love to use this, however without my bash prompt this is not worth the trouble caused by not having it.

**Comment by ChrisJohnsen** [comment]
How are you invoking the wrapper program? Through *tmux*’s `default-command`? Did you include the `-l` option? *bash* only uses `.bash_profile` if it is told to be a login shell.

**Comment by lawhorkl** [comment]
this is the line in my .tmux.conf file:

`set-option -g default-command "reattach-to-user-namespace -l zsh"`

**Comment by ChrisJohnsen** [comment]
Try changing `zsh` to `bash` in there.

**Comment by lawhorkl** [comment]
@ChrisJohnsen that appears to have worked! much thanks for the work involved in this!
