### ISSUE TITLE
What's the difference between `copy-pipe-and-cancel` and `copy-selection-and-cancel`? Where is the manual for these commands?

### ISSUE THREAD

**Issue by nnop** [ChrisJohnsen/tmux-MacOSX-pasteboard#67]

**Comment by ChrisJohnsen** [comment]
Those are *tmux* copy-mode commands; they don’t really have much to do with this software.

Most of the *tmux* documentation is in its manpage. But the copy-mode commands are only briefly mentioned there (many of the copy-mode commands are sufficiently self-describing).

The `copy-pipe` commands (the base command and the `-and-cancel` variant) send the selected text to a configuration-specified external command.

The `copy-selection` commands copy the selected text into an internal *tmux* paste buffer (and maybe also to an external clipboard; see the *tmux* manpage about `set-clipboard`).

**Comment by nnop** [comment]
It would be better if these commands have more detailed description. Thanks.
