### ISSUE TITLE
extra character showing

### ISSUE THREAD

**Issue by webkernel** [ChrisJohnsen/tmux-MacOSX-pasteboard#68]
Hi,

I use a Raspberry Pi 3 B+ to connect to my IRC community. I am using TMUX to create a new session.

$ tmux new -s session1

Inside session1 I run IRSSI and connect to my IRC channel.

Remotely, I am using iTerm2 to connect via ssh to my Pi3 and I run:

tmux attach -t session

Everything seems to be ok except for a thing that should be "P03a" and shows "P03aa". The same happens for "M08a"--> "M08aa". There's always the repetition of the last character.

In .tmux.conf I have the following line:

set -g default-terminal "screen-256color" # colors!

In iTerm2, Terminal is set to "xterm-256colors".

Any idea why is this happening?

Thanks

**Comment by ChrisJohnsen** [comment]
I don’t think I’ve seen anything like that before, but I have never used IRSSI.

I seems a bit like it might be a (re)drawing error of some sort.

I’d check that TERM is still `screen-256color` before you attach on the Pi (e.g. that its shell initialization files do not inappropriately change TERM). Or maybe the Pi might have an old/buggy terminfo database entry for the effective TERM that causes IRSSI to use an inappropriate control sequence (in which case you could use *infocmp* and *tic* to install a different terminfo entry).

If you feel comfortable manually interpreting terminal escape sequences, you might be able to use *script* to capture and replay the terminal output to try to narrow down the problem.

---

But it is unlikely that this has anything to do with the program(s) in this repository (even if you are using the wrapper on your Mac before sshing to the Pi).
