### ISSUE TITLE
Big Sur Warning Message

### ISSUE THREAD

**Issue by vinurs** [ChrisJohnsen/tmux-MacOSX-pasteboard#76]
```
$ /bin/pwd | reattach-to-user-namespace pbcopy
warning: reattach-to-user-namespace: unsupported new OS, trying as if it were 10.10
```

**Comment by ChrisJohnsen** [comment]
I cannot run Big Sur.

Can you verify whether — despite the warning — the wrapper still provides *necessary* functionality?
* Does (for example) `pbcopy` work without the wrapper?
    * If so, maybe the wrapper can be deprecated.
* If not, does using the wrapper let (e.g.) `pbcopy` work properly (if you ignore the warning)?
    * If so, we can just adjust the version checking logic for the warning.
* If not, someone will need to come up with an alternative method.

**Comment by vinurs** [comment]
@ChrisJohnsen sorry for reply late,  i've tried it now pbcopy can work without the wrapper
