### ISSUE TITLE
why not use iTerm2 that seems to have patched tmux and have it on the read mes

### ISSUE THREAD

**Issue by brando90** [ChrisJohnsen/tmux-MacOSX-pasteboard#77]
This worked for me: 

Using clipboard: https://stackoverflow.com/questions/12287432/how-to-copy-to-system-clipboard-from-tmux-output-after-mouse-selection
- have iTerm2 installed (https://iterm2.com/)
- allow terminal apps to use clipboard (https://stackoverflow.com/questions/12287432/how-to-copy-to-system-clipboard-from-tmux-output-after-mouse-selection)
- then select text and without letting go press option (nothing else, no need for command-c)
- then use usual command-v

**Comment by ChrisJohnsen** [comment]
Sure, these days there are other ways to get stuff onto the clipboard. Use whataver works best for your situation!
